"""Database layer: SQLite for local development, PostgreSQL (e.g. Neon) in production.

The backend is selected by the DATABASE_URL environment variable:
  - unset                            -> local SQLite file (DATABASE_PATH or <dir>/database.db)
  - postgresql://... (or postgres://) -> PostgreSQL via psycopg

Each function opens a short-lived connection, so the module is safe to use from a
threaded WSGI server (waitress) without sharing connections across threads. All
read functions return dict-style rows regardless of backend.
"""

from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parent

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

# Attribution columns added after the initial release; migrated in on startup.
ATTRIBUTION_COLUMNS = ("utm_source", "utm_medium", "utm_campaign", "referrer")

_INSERT_COLUMNS = (
    "email",
    "poll_answer",
    "created_at",
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "referrer",
)

if IS_POSTGRES:
    import psycopg as _psycopg
    from psycopg.rows import dict_row as _dict_row

    _DUPLICATE_ERRORS: tuple[type[Exception], ...] = (_psycopg.errors.UniqueViolation,)
else:
    _DUPLICATE_ERRORS = (sqlite3.IntegrityError,)


def _sqlite_path() -> str:
    return os.environ.get("DATABASE_PATH") or str(BASE_DIR / "database.db")


def _connect() -> Any:
    """Open a new connection to the active backend with dict-style rows."""
    if IS_POSTGRES:
        return _psycopg.connect(DATABASE_URL, row_factory=_dict_row)
    connection = sqlite3.connect(_sqlite_path())
    connection.row_factory = sqlite3.Row
    return connection


def _placeholders(count: int) -> str:
    token = "%s" if IS_POSTGRES else "?"
    return ", ".join([token] * count)


def _existing_columns(cursor: Any) -> set[str]:
    if IS_POSTGRES:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            ("submissions",),
        )
        return {row["column_name"] for row in cursor.fetchall()}
    cursor.execute("PRAGMA table_info(submissions)")
    return {row["name"] for row in cursor.fetchall()}


def init_db() -> None:
    """Create the submissions table and add any missing attribution columns."""
    id_clause = (
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if IS_POSTGRES
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    connection = _connect()
    try:
        cursor = connection.cursor()
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS submissions (
                {id_clause},
                email TEXT UNIQUE NOT NULL,
                poll_answer TEXT NOT NULL,
                created_at TEXT NOT NULL,
                utm_source TEXT,
                utm_medium TEXT,
                utm_campaign TEXT,
                referrer TEXT
            )
            """
        )
        existing = _existing_columns(cursor)
        for column in ATTRIBUTION_COLUMNS:
            if column not in existing:
                # Column names come from a fixed internal tuple, so this is safe.
                cursor.execute(f"ALTER TABLE submissions ADD COLUMN {column} TEXT")
        connection.commit()
    finally:
        connection.close()


def insert_submission(
    email: str, poll_answer: str, created_at: str, attribution: dict[str, str]
) -> bool:
    """Insert a signup. Returns False if the email is already registered."""
    values = (
        email,
        poll_answer,
        created_at,
        attribution.get("utm_source", ""),
        attribution.get("utm_medium", ""),
        attribution.get("utm_campaign", ""),
        attribution.get("referrer", ""),
    )
    sql = (
        f"INSERT INTO submissions ({', '.join(_INSERT_COLUMNS)}) "
        f"VALUES ({_placeholders(len(_INSERT_COLUMNS))})"
    )
    connection = _connect()
    try:
        cursor = connection.cursor()
        cursor.execute(sql, values)
        connection.commit()
        return True
    except _DUPLICATE_ERRORS:
        connection.rollback()
        return False
    finally:
        connection.close()


def poll_counts() -> dict[str, int]:
    """Return {poll_answer: count} across all submissions."""
    connection = _connect()
    try:
        cursor = connection.cursor()
        cursor.execute(
            "SELECT poll_answer, COUNT(*) AS count FROM submissions GROUP BY poll_answer"
        )
        return {row["poll_answer"]: int(row["count"]) for row in cursor.fetchall()}
    finally:
        connection.close()


def all_submissions() -> list[dict[str, Any]]:
    """All submissions as dicts, newest first (for CSV export)."""
    connection = _connect()
    try:
        cursor = connection.cursor()
        cursor.execute(
            "SELECT id, email, poll_answer, created_at, utm_source, utm_medium, "
            "utm_campaign, referrer FROM submissions ORDER BY created_at DESC"
        )
        return [dict(row) for row in cursor.fetchall()]
    finally:
        connection.close()
